name: My First Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build the project
        run: npm install && npm run build
      - name: Sets the vercel env
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo "{\"projectId\":\"$VERCEL_PROJECT_ID\",\"orgId\":\"$VERCEL_ORG_ID\"}" > project.json
      - name: Deploying the project
        run: npm run deploy
      - name: Steup finish
        run: echo "hurray!"
