name: My First Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build the project
        run: npm install && npm run build
      - name: Deploying the project
        env:
          VERCEL_ORG_ID: dzEfP5N1YHyaVXJUtQLFL8DF
          VERCEL_PROJECT_ID: prj_hUqIf5d8WYB0KtJOMJ5kLn5MX62j
        run: npm run deploy
      - name: Steup finish
        run: echo "hurray!"
